# Default configuration
example.config-reader.file.path=src/main/resources/application.properties
quarkus.log.level=INFO


# Profile-specific configuration
#%test.example.config-reader.file.path=src/test/resources/test-config-file.txt
%test.example.config-reader.file.path=src/test/resources/application.properties