# Default configuration
example.config-reader.file.path=src/main/resources/application.properties
quarkus.log.level=INFO


# Profile-specific configuration
%test1.example.config-reader.file.path=src/test/resources/application-test1.properties
%test2.example.config-reader.file.path=src/test/resources/application-test2.properties
%test3.example.config-reader.file.path=src/test/resources/application-test3.properties
%test4.example.config-reader.file.path=src/test/resources/application-test4.properties