package org.jpristas.thesis.quarkus.multiconfig.env.it;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;

@QuarkusTest
public class ExampleCodeGeneratorResourceTest {

    @Test
    public void testExampleGeneratedFileContentEndpoint() {
        given()
                .when().get("/quarkus-multiconfig-env/example-code-generator")
                .then()
                .statusCode(200)
                .body(is("This text file was generated by your Quarkus extension."));
    }
}
